#ifndef DEFINES_H
#define DEFINES_H

#define W_W 1280
#define W_H 1024

#define LOOP_SLEEP_US (1000000 / 60)
#define SIM_DT (1.0 / 60.0)
#define SIM_SKIP_RENDER_FRAMES 10
#define SIM_WR_TELEM 0

#define SIM_LOOP_SLEEP_STEP_US 100

#define CREATURE_MAX_SPEED 40.0
#define CREATURE_MAX_ROT_SPEED_DPS 40.0

#define CREATURE_TRAJECTORY_SIZE 64
#define CREATURE_TRAJECTORY_MIN_STEP 5
#define CREATURE_FOV_DEGS 80
#define CREATURE_BEAM_R 164
#define CREATURE_R 12
#define CREATURE_MEM_MAX 16
#define CREATURE_DELTA_ANGLE_ROT_DEGS 10
#define CREATURE_ROT_P_K 0.5
#define CREATURE_ROT_D_K 50.0
#define CREATURE_DELTA_DIST 10
#define CREATURE_SPD_P_K 0.3
#define CREATURE_NO_FRUIT_RND_USEC (5 * 1000000)
#define CREATURE_RND_TARGET_ATTEMPTS 32
#define CREATURE_RND_MIN_TARGET_DIST 256
#define CREATURE_RND_MIN_TARGET_APPROACH_DIST 64

#define CREATURE_MASS 1
#define CREATURE_ANGM 1

#define CREATURE_FWDFMAX 10
#define CREATURE_ANGFMAX 10

#define FRUIT_R 4
#define FRUIT_MEM_MARGIN 3

#endif // DEFINES_H
